install.packages("jsonlite",repos = "http://cran.rstudio.com/")
install.packages("xts",repos = "http://cran.rstudio.com/")
install.packages("dygraphs",repos = "http://cran.rstudio.com/")
install.packages("PerformanceAnalytics",repos = "http://cran.rstudio.com/")
install.packages("quantmod",repos = "http://cran.rstudio.com/")
install.packages("lattice",repos = "http://cran.rstudio.com/")
install.packages("ggplot2",repos = "http://cran.rstudio.com/")
install.packages("lubridate",repos = "http://cran.rstudio.com/")
install.packages("scales",repos = "http://cran.rstudio.com/")
install.packages("rmarkdown",repos = "http://cran.rstudio.com/")
install.packages("extrafont",repos = "http://cran.rstudio.com/")
install.packages("rjson",repos = "http://cran.rstudio.com/")
install.packages("svglite",repos = "http://cran.rstudio.com/")

library(extrafont)
font_import(prompt = FALSE)
